
import java.text.NumberFormat;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author max
 */
public class OctopusCard extends javax.swing.JFrame {

    /**
     * Creates new form OctopusCard
     */
    public OctopusCard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        octopusInstruction = new javax.swing.JLabel();
        enterOctopus = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        resetButton = new javax.swing.JButton();
        enterOctopusLastNo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        proceedToNext = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        octopusInstruction.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        octopusInstruction.setForeground(new java.awt.Color(0, 0, 255));
        octopusInstruction.setText("Please Enter Your Octopus Number:");
        getContentPane().add(octopusInstruction, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 109, 431, 44));

        enterOctopus.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        enterOctopus.setText("11111111");
        enterOctopus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterOctopusActionPerformed(evt);
            }
        });
        getContentPane().add(enterOctopus, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 193, -1, -1));

        jLabel1.setText("Example : 11111111 (1)");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 171, -1, -1));

        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });
        getContentPane().add(resetButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 264, -1, -1));

        enterOctopusLastNo.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        enterOctopusLastNo.setText("1");
        getContentPane().add(enterOctopusLastNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 193, -1, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel2.setText("(");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 198, -1, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel3.setText(")");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 198, -1, -1));

        proceedToNext.setText("Proceed");
        proceedToNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proceedToNextActionPerformed(evt);
            }
        });
        getContentPane().add(proceedToNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 264, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/bg1.jpeg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-180, 0, 640, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        // TODO add your handling code here:
        enterOctopus.setText("");
        enterOctopusLastNo.setText("");
    }//GEN-LAST:event_resetButtonActionPerformed

    private void proceedToNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proceedToNextActionPerformed
        // TODO add your handling code here:
        int confirmButton = JOptionPane.showConfirmDialog (null, "Proceed?","CONFIRM WINDOW",JOptionPane.YES_NO_OPTION,JOptionPane.INFORMATION_MESSAGE);
        if (confirmButton == JOptionPane.YES_NO_OPTION){
            TransferSuccess ts = new TransferSuccess();
            ts.setVisible(true);
            }else{
            
        }
    }//GEN-LAST:event_proceedToNextActionPerformed

    private void enterOctopusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterOctopusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enterOctopusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OctopusCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OctopusCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OctopusCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OctopusCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OctopusCard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField enterOctopus;
    private javax.swing.JTextField enterOctopusLastNo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel octopusInstruction;
    private javax.swing.JButton proceedToNext;
    private javax.swing.JButton resetButton;
    // End of variables declaration//GEN-END:variables
}
